export default class ActionsType {

    static CALL_API_SUCCESS = 'CALL_API_SUCCESS'
    static CALL_API_ERROR = 'CALL_API_ERROR'
    static T_GET_ALL_LIST_POST = 'GET_ALL_LIST_POST'
    static T_GET_LIST_SEARCH_BY_KEYWORD = 'GET_LIST_SEARCH_BY_KEYWORD'
    static GET_COUNT_SEARCH_BY_KEYWORD_TYPE = 'GET_COUNT_SEARCH_BY_KEYWORD_TYPE'
    static GET_DATA_SEARCH_BY_KEYWORD_PAGE = 'GET_DATA_SEARCH_BY_KEYWORD_PAGE'
    static GET_DETAIL_POST = 'GET_DETAIL_POST'
    static GET_SUGGESTIONS = 'GET_SUGGESTIONS'
    static UPDATE_KEY_SEARCH = 'UPDATE_KEY_SEARCH'
}